export const ActionTypes = {
    GET_CONTACTS: 'GET_CONTACTS',

    GET_CONTACT: 'GET_CONTACT',

    DELETE_CONTACT: 'DELETE_CONTACT',

    ADD_CONTACT: 'POST_CONTACT',

    CHANGE_CONTACT: 'CHANGE_CONTACT',

};
